apiVersion: v1
data:
  AUTH_TYPE: "{{ .Values.django.authType}}"
  {{ if eq .Values.django.authType "auth0" }}
  AUTH0_CLIENT_ID: "{{ .Values.django.auth0ClientId }}"
  AUTH0_DOMAIN: "{{ .Values.django.auth0Domain }}"
  {{ else if eq .Values.django.authType "authing" }}
  AUTHING_APP_ID: "{{ .Values.django.authingAppId }}"
  AUTHING_DOMAIN: "{{ .Values.django.authingDomain }}"
  {{- end }}
  CELERY_FLOWER_USER: "{{ .Values.flower.user }}"
  CELERY_FLOWER_PASSWORD: "{{ .Values.flower.password }}"
  DJANGO_LOG_LEVEL: "INFO"
  MODEL_FAMILIES: '{{ .Values.django.modelFamilies | toJson }}'
  VECTOR_DB_CONTEXT: '{{ .Values.django.vectorDBContext }}'
  VECTOR_DB_TYPE: "{{ .Values.django.vectorDBType }}"
  {{- if .Values.django.openaiAPIKey }}
  OPENAI_API_KEY: "{{ .Values.django.openaiAPIKey }}"
  {{- end}}
  {{- if .Values.django.openaiProxy }}
  OPENAI_API_PROXY: "{{ .Values.django.openaiProxy }}"
  {{- end}}
  FEISHU_APP_ID: "{{ .Values.django.feishu.appID }}"
  FEISHU_APP_SECRET: "{{ .Values.django.feishu.appSecret }}"
  FEISHU_ENCRYPT_KEY: "{{ .Values.django.feishu.encryptKey }}"
  MAX_BOT_COUNT: "{{ .Values.django.quota.maxBotCount }}"
  MAX_COLLECTION_COUNT: "{{ .Values.django.quota.maxCollectionCount }}"
  MAX_DOCUMENT_COUNT: "{{ .Values.django.quota.maxDocumentCount }}"
  MAX_CONVERSATION_COUNT: "{{ .Values.django.quota.maxConversationCount }}"
  EMBEDDING_MODEL: "{{ .Values.django.embeddingModel }}"
  EMBEDDING_DEVICE: "{{ .Values.django.embeddingDevice }}"
  EMBEDDING_BACKEND: "{{ .Values.django.embeddingBackend }}"
  EMBEDDING_SERVICE_URL: "{{ .Values.django.embeddingServiceUrl }}"
  EMBEDDING_SERVICE_MODEL: "{{ .Values.django.embeddingServiceModel }}"
  EMBEDDING_SERVICE_MODEL_UID: "{{ .Values.django.embeddingServiceModelUid }}"
  RERANK_BACKEND: "{{ .Values.django.rerankBackend }}"
  RERANK_SERVICE_URL: "{{ .Values.django.rerankServiceUrl }}"
  RERANK_SERVICE_MODEL_UID: "{{ .Values.django.rerankServiceModelUid }}"
  ENABLE_QA_GENERATOR: "{{ .Values.django.enableQAGenerator }}"
  ES_HOST: "{{ .Values.django.esHost }}"
  WHISPER_HOST: "{{ .Values.django.whisperHost }}"
  PADDLEOCR_HOST: "{{ .Values.django.paddleocrHost }}"
kind: ConfigMap
metadata:
  labels:
    {{- include "kubechat.labels" . | nindent 4 }}
  name: kubechat-config
