# Generated by Django 5.0.14 on 2025-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperag', '0020_delete_botintegration'),
    ]

    operations = [
        migrations.RunSQL(
                "alter table aperag_document drop constraint aperag_document_collection_id_1090ebaf_fk;",
            ),
    ] 