# Generated by Django 5.0.14 on 2025-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperag', '0020_delete_botintegration'),
    ]

    operations = [
        migrations.RunSQL(
                "alter table aperag_document drop constraint aperag_document_collection_id_1090ebaf_fk;",
            ),
        migrations.RunSQL(
                "alter table aperag_chat drop constraint aperag_chat_bot_id_7b595387_fk;",
            ),
        migrations.RunSQL(
                "alter table aperag_messagefeedback drop constraint aperag_messagefeedba_collection_id_dc4e351f_fk_aperag_co;",
            ),
        migrations.RunSQL(
                "alter table aperag_messagefeedback drop constraint aperag_messagefeedback_chat_id_1109b364_fk;",
            ),
        migrations.RunSQL(
                "alter table aperag_question drop constraint aperag_question_collection_id_268ff5d0_fk_aperag_collection_id;",
            ),
    ] 