{{- if and .Values.efsId (ne .Values.efsId "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmserver-efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
{{- end }}