/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Collection } from './collection';

/**
 * Message format for agent-type bots with additional capabilities
 * @export
 * @interface AgentMessage
 */
export interface AgentMessage {
    /**
     * User query
     * @type {string}
     * @memberof AgentMessage
     */
    'query': string;
    /**
     * The collection object to search in
     * @type {Collection}
     * @memberof AgentMessage
     */
    'collection': Collection;
    /**
     * LLM model to use for response generation
     * @type {string}
     * @memberof AgentMessage
     */
    'model_name'?: string;
    /**
     * Whether to enable web search
     * @type {boolean}
     * @memberof AgentMessage
     */
    'web_search_enabled'?: boolean;
}

