/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CleanupTempDocumentsRequest
 */
export interface CleanupTempDocumentsRequest {
    /**
     * List of temporary document IDs to cleanup
     * @type {Array<string>}
     * @memberof CleanupTempDocumentsRequest
     */
    'document_ids': Array<string>;
}

