/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConfirmDocumentsResponseFailedDocumentsInner } from './confirm-documents-response-failed-documents-inner';

/**
 * 
 * @export
 * @interface CleanupTempDocumentsResponse
 */
export interface CleanupTempDocumentsResponse {
    /**
     * Number of documents successfully deleted
     * @type {number}
     * @memberof CleanupTempDocumentsResponse
     */
    'deleted_count': number;
    /**
     * Number of documents that failed to delete
     * @type {number}
     * @memberof CleanupTempDocumentsResponse
     */
    'failed_count': number;
    /**
     * Details of failed deletions
     * @type {Array<ConfirmDocumentsResponseFailedDocumentsInner>}
     * @memberof CleanupTempDocumentsResponse
     */
    'failed_documents'?: Array<ConfirmDocumentsResponseFailedDocumentsInner>;
}

