/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MergeSuggestionItem } from './merge-suggestion-item';

/**
 * Response containing node merge suggestions
 * @export
 * @interface MergeSuggestionsResponse
 */
export interface MergeSuggestionsResponse {
    /**
     * List of merge suggestions ordered by confidence score (highest first)
     * @type {Array<MergeSuggestionItem>}
     * @memberof MergeSuggestionsResponse
     */
    'suggestions': Array<MergeSuggestionItem>;
    /**
     * Whether suggestions were loaded from cache
     * @type {boolean}
     * @memberof MergeSuggestionsResponse
     */
    'from_cache': boolean;
    /**
     * Generation timestamp
     * @type {string}
     * @memberof MergeSuggestionsResponse
     */
    'generated_at': string;
}

