/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to merge two graph nodes
 * @export
 * @interface NodeMergeRequest
 */
export interface NodeMergeRequest {
    /**
     * First entity ID to merge
     * @type {string}
     * @memberof NodeMergeRequest
     */
    'entity_id1': string;
    /**
     * Second entity ID to merge
     * @type {string}
     * @memberof NodeMergeRequest
     */
    'entity_id2': string;
}

