/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response containing node merge results
 * @export
 * @interface NodeMergeResponse
 */
export interface NodeMergeResponse {
    /**
     * Status of the merge operation
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'status': NodeMergeResponseStatusEnum;
    /**
     * Detailed message about the merge operation
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'message': string;
    /**
     * The entity that was kept (merge target)
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'target_entity'?: string;
    /**
     * The entity that was merged (merge source)
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'source_entity'?: string;
    /**
     * Number of edges that were redirected during merge
     * @type {number}
     * @memberof NodeMergeResponse
     */
    'redirected_edges'?: number;
    /**
     * Length of the merged description
     * @type {number}
     * @memberof NodeMergeResponse
     */
    'merged_description_length'?: number;
    /**
     * Whether LLM was used to summarize descriptions
     * @type {boolean}
     * @memberof NodeMergeResponse
     */
    'used_llm_summary'?: boolean;
    /**
     * Collection ID where the merge was performed
     * @type {string}
     * @memberof NodeMergeResponse
     */
    'collection_id'?: string;
}

export const NodeMergeResponseStatusEnum = {
    success: 'success',
    error: 'error'
} as const;

export type NodeMergeResponseStatusEnum = typeof NodeMergeResponseStatusEnum[keyof typeof NodeMergeResponseStatusEnum];


