/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Web search request
 * @export
 * @interface WebSearchRequest
 */
export interface WebSearchRequest {
    /**
     * Search query
     * @type {string}
     * @memberof WebSearchRequest
     */
    'query': string;
    /**
     * Maximum number of results to return
     * @type {number}
     * @memberof WebSearchRequest
     */
    'max_results'?: number;
    /**
     * Search engine to use
     * @type {string}
     * @memberof WebSearchRequest
     */
    'search_engine'?: string;
    /**
     * Request timeout in seconds
     * @type {number}
     * @memberof WebSearchRequest
     */
    'timeout'?: number;
    /**
     * Browser locale
     * @type {string}
     * @memberof WebSearchRequest
     */
    'locale'?: string;
    /**
     * Domain or URL for targeted processing. Can be a domain name (e.g., \'vercel.com\') or URL (e.g., \'https://vercel.com/docs/llms.txt\'). When provided, the system will discover LLM-optimized content (llms.txt) and perform site-specific searches.
     * @type {string}
     * @memberof WebSearchRequest
     */
    'source'?: string;
    /**
     * Strict domain limitation flag. When true, only returns results from the domain specified in \'source\'. When false (default), may include additional relevant results from other domains. Has no effect when \'source\' is empty.
     * @type {boolean}
     * @memberof WebSearchRequest
     */
    'use_source_domain_only'?: boolean;
    /**
     * Enable LLM.txt discovery search. When true, searches for LLM-optimized content indexes (llms.txt files) from the specified domain in \'source\'. When \'source\' is not provided, this feature is silently skipped. LLM.txt files provide AI-optimized content summaries and documentation.
     * @type {boolean}
     * @memberof WebSearchRequest
     */
    'search_llms_txt'?: boolean;
}

