apiVersion: v1
kind: Secret
metadata:
  name: aperag-env
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
    # Auth
    AUTH_TYPE={{ .Values.django.env.AUTH_TYPE }}
    AUTH0_DOMAIN={{ .Values.django.env.AUTH0_DOMAIN }}
    AUTH0_CLIENT_ID={{ .Values.django.env.AUTH0_CLIENT_ID }}
    AUTHING_DOMAIN={{ .Values.django.env.AUTHING_DOMAIN }}
    AUTHING_APP_ID={{ .Values.django.env.AUTHING_APP_ID }}
    LOGTO_DOMAIN={{ .Values.django.env.LOGTO_DOMAIN }}
    LOGTO_APP_ID={{ .Values.django.env.LOGTO_APP_ID }}
    
    # Logging
    DJANGO_LOG_LEVEL={{ .Values.django.env.DJANGO_LOG_LEVEL }}
    
    # Celery
    CELERY_FLOWER_USER={{ .Values.django.env.CELERY_FLOWER_USER }}
    CELERY_FLOWER_PASSWORD={{ .Values.django.env.CELERY_FLOWER_PASSWORD }}
    
    # Vector DB
    VECTOR_DB_TYPE={{ .Values.django.env.VECTOR_DB_TYPE }}
    VECTOR_DB_CONTEXT={{ .Values.django.env.VECTOR_DB_CONTEXT }}
    
    # Object Store
    OBJECT_STORE_TYPE={{ .Values.django.env.OBJECT_STORE_TYPE }}
    {{- if eq .Values.django.env.OBJECT_STORE_TYPE "local" }}
    OBJECT_STORE_LOCAL_ROOT_DIR={{ .Values.django.env.OBJECT_STORE_LOCAL_ROOT_DIR }}
    {{- end }}
    {{- if eq .Values.django.env.OBJECT_STORE_TYPE "s3" }}
    OBJECT_STORE_S3_ENDPOINT={{ .Values.django.env.OBJECT_STORE_S3_ENDPOINT }}
    OBJECT_STORE_S3_REGION={{ .Values.django.env.OBJECT_STORE_S3_REGION }}
    OBJECT_STORE_S3_ACCESS_KEY={{ .Values.django.env.OBJECT_STORE_S3_ACCESS_KEY }}
    OBJECT_STORE_S3_SECRET_KEY={{ .Values.django.env.OBJECT_STORE_S3_SECRET_KEY }}
    OBJECT_STORE_S3_BUCKET={{ .Values.django.env.OBJECT_STORE_S3_BUCKET }}
    OBJECT_STORE_S3_PREFIX_PATH={{ .Values.django.env.OBJECT_STORE_S3_PREFIX_PATH }}
    OBJECT_STORE_S3_USE_PATH_STYLE={{ .Values.django.env.OBJECT_STORE_S3_USE_PATH_STYLE }}
    {{- end }}
    
    # doc-ray
    DOCRAY_HOST={{ .Values.django.env.DOCRAY_HOST }}
    
    DEBUG={{ .Values.django.env.DEBUG }}
    FEISHU_APP_ID={{ .Values.django.env.FEISHU_APP_ID }}
    FEISHU_APP_SECRET={{ .Values.django.env.FEISHU_APP_SECRET }}
    {{- if .Values.django.env.FEISHU_ENCRYPT_KEY }}
    FEISHU_ENCRYPT_KEY={{ .Values.django.env.FEISHU_ENCRYPT_KEY }}
    {{- end }}
    
    MAX_BOT_COUNT={{ .Values.django.env.MAX_BOT_COUNT }}
    MAX_COLLECTION_COUNT={{ .Values.django.env.MAX_COLLECTION_COUNT }}
    MAX_DOCUMENT_COUNT={{ .Values.django.env.MAX_DOCUMENT_COUNT }}
    MAX_CONVERSATION_COUNT={{ .Values.django.env.MAX_CONVERSATION_COUNT }}
    
    EMBEDDING_MAX_CHUNKS_IN_BATCH={{ .Values.django.env.EMBEDDING_MAX_CHUNKS_IN_BATCH }}
    
    # Chunking
    CHUNK_SIZE={{ .Values.django.env.CHUNK_SIZE }}
    CHUNK_OVERLAP_SIZE={{ .Values.django.env.CHUNK_OVERLAP_SIZE }}
    
    TIKTOKEN_CACHE_DIR={{ .Values.django.env.TIKTOKEN_CACHE_DIR }}
    DEFAULT_ENCODING_MODEL={{ .Values.django.env.DEFAULT_ENCODING_MODEL }}
    TOKENIZERS_PARALLELISM={{ .Values.django.env.TOKENIZERS_PARALLELISM }}
    
    # LightRAG
    LIGHTRAG_KV_STORAGE={{ .Values.django.env.LIGHTRAG_KV_STORAGE }}
    LIGHTRAG_VECTOR_STORAGE={{ .Values.django.env.LIGHTRAG_VECTOR_STORAGE }}
    LIGHTRAG_GRAPH_STORAGE={{ .Values.django.env.LIGHTRAG_GRAPH_STORAGE }}
    LIGHTRAG_DOC_STATUS_STORAGE={{ .Values.django.env.LIGHTRAG_DOC_STATUS_STORAGE }}