apiVersion: v1
kind: Secret
metadata:
  name: aperag-env
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
    # Database
    POSTGRES_HOST={{ .Values.django.metaDBHost | default "aperag-postgres" }}
    POSTGRES_PORT={{ .Values.django.metaDBPort | default "5432" }}
    POSTGRES_DB={{ .Values.django.metaDBDatabase | default "aperag" }}
    POSTGRES_USER={{ .Values.django.metaDBUsername | default "postgres" }}
    POSTGRES_PASSWORD={{ .Values.django.metaDBPassword | default "postgres" }}
    DATABASE_URL="postgres://{{ .Values.django.metaDBUsername | default "postgres" }}:{{ .Values.django.metaDBPassword | default "postgres" }}@{{ .Values.django.metaDBHost | default "aperag-postgres" }}:{{ .Values.django.metaDBPort | default "5432" }}/{{ .Values.django.metaDBDatabase | default "aperag" }}"
    
    # Redis
    REDIS_HOST={{ .Values.django.redisHost | default "aperag-redis" }}
    REDIS_PORT={{ .Values.django.redisPort | default "6379" }}
    REDIS_USERNAME={{ .Values.django.redisUsername | default "default" }}
    REDIS_PASSWORD={{ .Values.django.redisPassword | default "password" }}
    MEMORY_REDIS_URL=redis://{{ .Values.django.redisUsername | default "default" }}:{{ .Values.django.redisPassword | default "password" }}@{{ .Values.django.redisHost | default "aperag-redis" }}:{{ .Values.django.redisPort | default "6379" }}
    CELERY_BROKER_URL=redis://{{ .Values.django.redisUsername | default "default" }}:{{ .Values.django.redisPassword | default "password" }}@{{ .Values.django.redisHost | default "aperag-redis" }}:{{ .Values.django.redisPort | default "6379" }}/0
    
    # Vector DB
    VECTOR_DB_TYPE={{ .Values.django.vectorDBType | default "qdrant" }}
    VECTOR_DB_CONTEXT='{{ .Values.django.vectorDBContext | default "{\"url\":\"http://aperag-qdrant\", \"port\":6333, \"distance\":\"Cosine\", \"timeout\": 1000}" }}'
    
    # Elasticsearch
    ES_HOST={{ .Values.django.esHost | default "http://aperag-es:9200" }}
    
    # Object Storage
    OBJECT_STORE_TYPE={{ .Values.django.objectStoreType | default "local" }}
    OBJECT_STORE_LOCAL_ROOT_DIR={{ .Values.django.objectStoreLocalRootDir | default "/data/objects" }}
    {{- if eq .Values.django.objectStoreType "s3" }}
    OBJECT_STORE_S3_ENDPOINT={{ .Values.django.objectStoreS3Endpoint }}
    OBJECT_STORE_S3_REGION={{ .Values.django.objectStoreS3Region | default "" }}
    OBJECT_STORE_S3_ACCESS_KEY={{ .Values.django.objectStoreS3AccessKey }}
    OBJECT_STORE_S3_SECRET_KEY={{ .Values.django.objectStoreS3SecretKey }}
    OBJECT_STORE_S3_BUCKET={{ .Values.django.objectStoreS3Bucket | default "aperag" }}
    OBJECT_STORE_S3_PREFIX_PATH={{ .Values.django.objectStoreS3PrefixPath | default "" }}
    OBJECT_STORE_S3_USE_PATH_STYLE={{ .Values.django.objectStoreS3UsePathStyle | default "True" }}
    {{- end }}
    
    # Celery Flower
    CELERY_FLOWER_USER={{ .Values.flower.user | default "admin" }}
    CELERY_FLOWER_PASSWORD={{ .Values.flower.password | default "admin" }}
    
    # Auth
    AUTH_TYPE={{ .Values.django.authType | default "cookie" }}
    {{- if eq .Values.django.authType "auth0" }}
    AUTH0_DOMAIN={{ .Values.django.auth0Domain }}
    AUTH0_CLIENT_ID={{ .Values.django.auth0ClientId }}
    {{- else if eq .Values.django.authType "authing" }}
    AUTHING_DOMAIN={{ .Values.django.authingDomain }}
    AUTHING_APP_ID={{ .Values.django.authingAppId }}
    {{- else if eq .Values.django.authType "logto" }}
    LOGTO_DOMAIN={{ .Values.django.logtoDomain }}
    LOGTO_APP_ID={{ .Values.django.logtoAppId }}
    {{- end }}
    
    # Logging
    DJANGO_LOG_LEVEL={{ .Values.django.logLevel | default "INFO" }}
    
    # Feishu
    FEISHU_APP_ID={{ .Values.django.feishu.appID | default "" }}
    FEISHU_APP_SECRET={{ .Values.django.feishu.appSecret | default "" }}
    FEISHU_ENCRYPT_KEY={{ .Values.django.feishu.encryptKey | default "" }}
    
    # Quota
    MAX_BOT_COUNT={{ .Values.django.quota.maxBotCount | default "10" }}
    MAX_COLLECTION_COUNT={{ .Values.django.quota.maxCollectionCount | default "50" }}
    MAX_DOCUMENT_COUNT={{ .Values.django.quota.maxDocumentCount | default "1000" }}
    MAX_CONVERSATION_COUNT={{ .Values.django.quota.maxConversationCount | default "100" }}
    
    # Chunking
    CHUNK_SIZE={{ .Values.django.chunkSize | default "400" }}
    CHUNK_OVERLAP_SIZE={{ .Values.django.chunkOverlapSize | default "20" }}
    
    # Embedding
    EMBEDDING_MAX_CHUNKS_IN_BATCH={{ .Values.django.embeddingMaxChunksInBatch | default "16" }}
    
    # Rerank
    RERANK_BACKEND={{ .Values.django.rerankBackend | default "jina_ai" }}
    RERANK_SERVICE_URL={{ .Values.django.rerankServiceUrl | default "https://api.jina.ai/v1/rerank" }}
    RERANK_SERVICE_MODEL={{ .Values.django.rerankServiceModel | default "jina-reranker-v2-base-multilingual" }}
    RERANK_SERVICE_TOKEN_API_KEY={{ .Values.django.rerankServiceTokenApiKey | default "" }}
    
    # Tokenizer
    TIKTOKEN_CACHE_DIR=/root/.cache/tiktoken
    DEFAULT_ENCODING_MODEL=cl100k_base
    TOKENIZERS_PARALLELISM=false
    
    # Media
    MEDIA_ROOT=/data/media
    
    # Admin
    ADMIN_USER={{ .Values.django.adminUser | default "admin" }}
    ADMIN_TOKEN={{ .Values.django.adminToken | default "" }}
    
    # OpenAI
    {{- if .Values.django.openaiAPIKey }}
    OPENAI_API_KEY={{ .Values.django.openaiAPIKey }}
    {{- end }}
    {{- if .Values.django.openaiProxy }}
    OPENAI_API_PROXY={{ .Values.django.openaiProxy }}
    {{- end }}
    {{- if .Values.django.openaiAPIBase }}
    OPENAI_API_BASE={{ .Values.django.openaiAPIBase }}
    {{- end }}
    
    # Azure OpenAI
    {{- if .Values.django.azureOpenAIAPIVersion }}
    AZURE_OPENAI_API_VERSION={{ .Values.django.azureOpenAIAPIVersion }}
    {{- end }}
    {{- if .Values.django.azureOpenAIDeploymentName }}
    AZURE_OPENAI_DEPLOYMENT_NAME={{ .Values.django.azureOpenAIDeploymentName }}
    {{- end }}
    {{- if .Values.django.azureOpenAIAPIKey }}
    AZURE_OPENAI_API_KEY={{ .Values.django.azureOpenAIAPIKey }}
    {{- end }}
    {{- if .Values.django.azureOpenAIAPIBase }}
    AZURE_OPENAI_API_BASE={{ .Values.django.azureOpenAIAPIBase }}
    {{- end }}
    
    # Email
    EMAIL_HOST={{ .Values.django.emailHost | default "smtp.gmail.com" }}
    EMAIL_PORT={{ .Values.django.emailPort | default "587" }}
    EMAIL_USE_TLS={{ .Values.django.emailUseTls | default "True" }}
    EMAIL_HOST_USER={{ .Values.django.emailHostUser | default "" }}
    EMAIL_HOST_PASSWORD={{ .Values.django.emailHostPassword | default "" }}
    DEFAULT_FROM_EMAIL={{ .Values.django.defaultFromEmail | default "noreply@aperag.com" }}
    SITE_URL={{ .Values.django.siteUrl | default "http://localhost:8000" }}
    
    # Registration
    REGISTER_MODE={{ .Values.django.registerMode | default "unlimited" }}
    
    # Chat
    CHAT_CONSUMER_IMPLEMENTATION={{ .Values.django.chatConsumerImplementation | default "document-qa" }} 