apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
    {{- include "api.labels" . | nindent 4 }}
  name: aperag
spec:
  ports:
    - name: "api"
      port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
  selector:
    {{- include "aperag.selectorLabels" . | nindent 4 }}
    {{- include "api.labels" . | nindent 4 }}
