apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/aperag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: celeryworker
spec:
  replicas: {{ index .Values "celery-worker" "replicaCount" }}
  selector:
    matchLabels:
      {{- include "aperag.selectorLabels" . | nindent 6 }}
      {{- include "celeryworker.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aperag.selectorLabels" . | nindent 8 }}
        {{- include "celeryworker.labels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |
              mkdir -p /data/.cache
              mkdir -p /root/.cache
              ln -s /data/.cache/huggingface /root/.cache/
              ln -s /data/.cache/torch /root/.cache/
              /app/scripts/entrypoint.sh /app/scripts/start-celery-worker.sh
          env:
            - name: REDIS_HOST
              value: {{ .Values.django.redisHost | quote }}
            - name: REDIS_PORT
              value: {{ .Values.django.redisPort | quote }}
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.redisSecret }}
                  key: username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.redisSecret }}
                  key: password
            - name: DJANGO_LOG_LEVEL
              value: {{ .Values.django.logLevel | quote }}
            - name: POSTGRES_DB
              value: "{{ .Values.django.metaDBDatabase }}"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: password

            - name: VECTOR_DB_CONTEXT
              value: {{ .Values.django.vectorDBContext | quote }}
            - name: VECTOR_DB_TYPE
              value: {{ .Values.django.vectorDBType | quote }}
            - name: MEDIA_ROOT
              value: /data/media
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: EMBEDDING_MODEL
              value: {{ .Values.django.embeddingModel | quote }}
            - name: EMBEDDING_DEVICE
              value: {{ .Values.django.embeddingDevice | quote }}
            - name: EMBEDDING_BACKEND
              value: {{ .Values.django.embeddingBackend | quote }}
            - name: EMBEDDING_SERVICE_URL
              value: {{ .Values.django.embeddingServiceUrl | quote }}
            - name: EMBEDDING_SERVICE_MODEL
              value: {{ .Values.django.embeddingServiceModel | quote }}
            - name: EMBEDDING_SERVICE_MODEL_UID
              value: {{ .Values.django.embeddingServiceModelUid | quote }}
            - name: WHISPER_HOST
              value: {{ .Values.django.whisperHost | quote }}
            - name: PADDLEOCR_HOST
              value: {{ .Values.django.paddleocrHost | quote }}
            {{- if .Values.django.openaiAPIKey }}
            - name: OPENAI_API_KEY
              value: {{ .Values.django.openaiAPIKey | quote }}
            {{- end}}
            {{- if .Values.django.openaiProxy }}
            - name: OPENAI_API_PROXY
              value: {{ .Values.django.openaiProxy | quote }}
            {{- end}}
            - name: MODEL_FAMILIES
              value: {{ .Values.django.modelFamilies | toJson | quote }}
            - name: ES_HOST
              value: {{ .Values.django.esHost | quote }}
          image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: aperag-celeryworker
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with index .Values "celery-worker" "resources" }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      {{- with index .Values "celery-worker" "affinity" }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # shared uploaded files between django and celery
        - name: data
          hostPath:
            path: {{ .Values.django.dataPath }}
