apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/deeprag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "deeprag.labels" . | nindent 4 }}
    {{- include "django.labels" . | nindent 4 }}
  name: deeprag
spec:
  ports:
    - name: "api"
      port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
  selector:
    {{- include "deeprag.selectorLabels" . | nindent 4 }}
    {{- include "django.labels" . | nindent 4 }}
