apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -c -o deploy/aperag
    kompose.version: 1.26.0 (40646f47)
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: flower
spec:
  replicas: {{ .Values.flower.replicaCount }}
  selector:
    matchLabels:
      {{- include "aperag.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aperag.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |
              /app/scripts/entrypoint.sh /app/scripts/start-celery-flower.sh
          env:
            - name: REDIS_HOST
              value: {{ .Values.django.redisHost | quote }}
            - name: REDIS_PORT
              value: {{ .Values.django.redisPort | quote }}
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.redisSecret }}
                  key: username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.redisSecret }}
                  key: password
            - name: CELERY_FLOWER_PASSWORD
              value: {{ .Values.flower.password | quote }}
            - name: CELERY_FLOWER_USER
              value: {{ .Values.flower.user | quote }}
            - name: DJANGO_LOG_LEVEL
              value: {{ .Values.django.logLevel | quote }}
            - name: POSTGRES_DB
              value: "{{ .Values.django.metaDBDatabase }}"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.django.metaDBSecret }}
                  key: password
          image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: aperag-flower
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5555
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
status: {}
