apiVersion: v1
kind: Service
metadata:
  name: aperag-website
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: aperag-website
  type: {{ .Values.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: aperag-console
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 80
  selector:
    app: aperag-console
  type: {{ .Values.service.type }}
