apiVersion: v1
kind: Service
metadata:
  name: deeprag-website
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: deeprag-website
  type: {{ .Values.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: deeprag-console
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 80
  selector:
    app: deeprag-console
  type: {{ .Values.service.type }}
