apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "aperag.labels" . | nindent 4 }}
  name: aperag-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "aperag.selectorLabels" . | nindent 4 }}
    {{- include "frontend.labels" . | nindent 4 }}