apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aperag-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: aperag
            port:
              number: 8000
      - pathType: Prefix
        path: "/web"
        backend:
          service:
            name: aperag-console
            port:
              number: 8002
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: aperag-website
            port:
              number: 8001
    {{- if .Values.django.domainName }}
    host: {{ .Values.django.domainName }}
    {{- end }}