openapi: 3.0.0
info:
  title: ApeRAG API
  description: ApeRAG API Documentation
  version: 1.0.0
servers:
  - url: /api/v1
    description: API v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
    CookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
paths:
  # bots
  /bots:
    $ref: './paths/bots.yaml#/bots'
  /bots/{bot_id}:
    $ref: './paths/bots.yaml#/bot'

  # chats
  /bots/{bot_id}/chats:
    $ref: './paths/chats.yaml#/chats'
  /bots/{bot_id}/chats/{chat_id}:
    $ref: './paths/chats.yaml#/chat'
  /bots/{bot_id}/chats/{chat_id}/messages/{message_id}:
    $ref: './paths/message.yaml#/message'
  /bots/{bot_id}/web-chats:
    $ref: './paths/chats.yaml#/web_chats'
  /bots/{bot_id}/web-chats/{chat_id}:
    $ref: './paths/chats.yaml#/web_chat'
  /bots/{bot_id}/web-chats/{chat_id}/messages/{message_id}:
    $ref: './paths/message.yaml#/message'

  # collections
  /collections:
    $ref: './paths/collections.yaml#/collections'
  /collections/{collection_id}:
    $ref: './paths/collections.yaml#/collection'
  /collections/{collection_id}/documents:
    $ref: './paths/collections.yaml#/documents'
  /collections/{collection_id}/documents/{document_id}:
    $ref: './paths/collections.yaml#/document'
  /collections/{collection_id}/questions:
    $ref: './paths/collections.yaml#/questions'
  /collections/{collection_id}/questions/{question_id}:
    $ref: './paths/collections.yaml#/question'

  # apikeys
  /apikeys:
    $ref: './paths/apikeys.yaml#/apikeys'
  /apikeys/{apikey_id}:
    $ref: './paths/apikeys.yaml#/apikey'

  # models
  /models:
    $ref: './paths/models.yaml#/models'

  # config
  /config:
    $ref: './paths/config.yaml#/config'
  /prompt-templates:
    $ref: './paths/prompt_templates.yaml#/promptTemplates'

  # users
  /invite:
    $ref: './paths/auth.yaml#/invite'
  /invitations:
    $ref: './paths/auth.yaml#/invitations'
  /register:
    $ref: './paths/auth.yaml#/register'
  /login:
    $ref: './paths/auth.yaml#/login'
  /logout:
    $ref: './paths/auth.yaml#/logout'
  /users:
    $ref: './paths/auth.yaml#/users'
  /user:
    $ref: './paths/auth.yaml#/user'
  /change-password:
    $ref: './paths/auth.yaml#/changePassword'
  /users/{user_id}:
    $ref: './paths/auth.yaml#/deleteUser'