/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of bot
 * @export
 * @enum {string}
 */

export const BotType = {
    knowledge: 'knowledge',
    common: 'common',
    agent: 'agent'
} as const;

export type BotType = typeof BotType[keyof typeof BotType];



