/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IndexPrompts } from './index-prompts';
// May contain unused imports in some cases
// @ts-ignore
import type { KnowledgeGraphConfig } from './knowledge-graph-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelSpec } from './model-spec';

/**
 * 
 * @export
 * @interface CollectionConfig
 */
export interface CollectionConfig {
    /**
     * Source system identifier. Only `system` is supported.
     * @type {string}
     * @memberof CollectionConfig
     */
    'source'?: string;
    /**
     * Whether to enable vector index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_vector'?: boolean;
    /**
     * Whether to enable fulltext index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_fulltext'?: boolean;
    /**
     * Whether to enable knowledge graph index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_knowledge_graph'?: boolean;
    /**
     * Whether to enable summary index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_summary'?: boolean;
    /**
     * Whether to enable vision index
     * @type {boolean}
     * @memberof CollectionConfig
     */
    'enable_vision'?: boolean;
    /**
     * 
     * @type {KnowledgeGraphConfig}
     * @memberof CollectionConfig
     */
    'knowledge_graph_config'?: KnowledgeGraphConfig;
    /**
     * 
     * @type {IndexPrompts}
     * @memberof CollectionConfig
     */
    'index_prompts'?: IndexPrompts;
    /**
     * Language for the collection content and processing
     * @type {string}
     * @memberof CollectionConfig
     */
    'language'?: CollectionConfigLanguageEnum;
    /**
     * 
     * @type {ModelSpec}
     * @memberof CollectionConfig
     */
    'embedding'?: ModelSpec;
    /**
     * 
     * @type {ModelSpec}
     * @memberof CollectionConfig
     */
    'completion'?: ModelSpec;
}

export const CollectionConfigLanguageEnum = {
    zh_CN: 'zh-CN',
    en_US: 'en-US',
    ja_JP: 'ja-JP',
    ko_KR: 'ko-KR'
} as const;

export type CollectionConfigLanguageEnum = typeof CollectionConfigLanguageEnum[keyof typeof CollectionConfigLanguageEnum];


