/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPromptsRequest
 */
export interface ResetPromptsRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetPromptsRequest
     */
    'language': ResetPromptsRequestLanguageEnum;
    /**
     * Prompt types to reset, omit to reset all
     * @type {Array<string>}
     * @memberof ResetPromptsRequest
     */
    'types'?: Array<string>;
}

export const ResetPromptsRequestLanguageEnum = {
    zh_CN: 'zh-CN',
    en_US: 'en-US'
} as const;

export type ResetPromptsRequestLanguageEnum = typeof ResetPromptsRequestLanguageEnum[keyof typeof ResetPromptsRequestLanguageEnum];


