/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface TurnFeedback
 */
export interface TurnFeedback {
    /**
     *
     * @type {string}
     * @memberof TurnFeedback
     */
    'turn_id': string;
    /**
     *
     * @type {string}
     * @memberof TurnFeedback
     */
    'type': TurnFeedbackTypeEnum;
    /**
     *
     * @type {string}
     * @memberof TurnFeedback
     */
    'tag'?: TurnFeedbackTagEnum;
    /**
     *
     * @type {string}
     * @memberof TurnFeedback
     */
    'message'?: string;
    /**
     *
     * @type {string}
     * @memberof TurnFeedback
     */
    'created'?: string;
    /**
     *
     * @type {string}
     * @memberof TurnFeedback
     */
    'updated'?: string;
}

export const TurnFeedbackTypeEnum = {
    good: 'good',
    bad: 'bad'
} as const;

export type TurnFeedbackTypeEnum = typeof TurnFeedbackTypeEnum[keyof typeof TurnFeedbackTypeEnum];
export const TurnFeedbackTagEnum = {
    Harmful: 'Harmful',
    Unsafe: 'Unsafe',
    Fake: 'Fake',
    Unhelpful: 'Unhelpful',
    Other: 'Other'
} as const;

export type TurnFeedbackTagEnum = typeof TurnFeedbackTagEnum[keyof typeof TurnFeedbackTagEnum];
