/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateUserPromptsRequestPrompts } from './update-user-prompts-request-prompts';

/**
 * 
 * @export
 * @interface UpdateUserPromptsRequest
 */
export interface UpdateUserPromptsRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPromptsRequest
     */
    'language': UpdateUserPromptsRequestLanguageEnum;
    /**
     * 
     * @type {UpdateUserPromptsRequestPrompts}
     * @memberof UpdateUserPromptsRequest
     */
    'prompts': UpdateUserPromptsRequestPrompts;
}

export const UpdateUserPromptsRequestLanguageEnum = {
    zh_CN: 'zh-CN',
    en_US: 'en-US'
} as const;

export type UpdateUserPromptsRequestLanguageEnum = typeof UpdateUserPromptsRequestLanguageEnum[keyof typeof UpdateUserPromptsRequestLanguageEnum];


