/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserPromptsRequest
 */
export interface UpdateUserPromptsRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPromptsRequest
     */
    'language': UpdateUserPromptsRequestLanguageEnum;
    /**
     * Prompts to update
     * @type {{ [key: string]: string; }}
     * @memberof UpdateUserPromptsRequest
     */
    'prompts': { [key: string]: string; };
}

export const UpdateUserPromptsRequestLanguageEnum = {
    zh_CN: 'zh-CN',
    en_US: 'en-US'
} as const;

export type UpdateUserPromptsRequestLanguageEnum = typeof UpdateUserPromptsRequestLanguageEnum[keyof typeof UpdateUserPromptsRequestLanguageEnum];


