/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Web search request
 * @export
 * @interface WebSearchRequest
 */
export interface WebSearchRequest {
    /**
     * Search query for web search. Optional when using source-only site browsing.
     * @type {string}
     * @memberof WebSearchRequest
     */
    'query'?: string;
    /**
     * Maximum number of results to return
     * @type {number}
     * @memberof WebSearchRequest
     */
    'max_results'?: number;
    /**
     * Request timeout in seconds
     * @type {number}
     * @memberof WebSearchRequest
     */
    'timeout'?: number;
    /**
     * Browser locale
     * @type {string}
     * @memberof WebSearchRequest
     */
    'locale'?: string;
    /**
     * Domain or URL for site-specific filtering. When provided with query, limits search results to this domain (e.g., \'site:vercel.com query\').
     * @type {string}
     * @memberof WebSearchRequest
     */
    'source'?: string;
}

