"""empty message

Revision ID: 79bee6e5820c
Revises: d112e0332219
Create Date: 2025-09-22 11:25:03.518575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bee6e5820c'
down_revision: Union[str, None] = 'd112e0332219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('group_path', sa.String(length=1024), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_department_parent_id', 'department', ['parent_id'], unique=False)
    op.create_index('ix_department_tenant_id', 'department', ['tenant_id'], unique=False)
    op.add_column('user', sa.Column('department_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_column('user', 'department_id')
    op.drop_index('ix_department_tenant_id', table_name='department')
    op.drop_index('ix_department_parent_id', table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
