"""empty message

Revision ID: 009e18f0a094
Revises: 12ea6d2bf365
Create Date: 2025-06-13 10:07:21.204399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '009e18f0a094'
down_revision: Union[str, None] = '12ea6d2bf365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_index_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=24), nullable=False),
    sa.Column('index_type', sa.Enum('vector', 'fulltext', 'graph', name='documentindextype'), nullable=False),
    sa.Column('desired_state', sa.Enum('present', 'absent', name='indexdesiredstate'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'index_type', name='uq_document_index_spec')
    )
    op.create_index(op.f('ix_document_index_specs_desired_state'), 'document_index_specs', ['desired_state'], unique=False)
    op.create_index(op.f('ix_document_index_specs_document_id'), 'document_index_specs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_index_specs_id'), 'document_index_specs', ['id'], unique=False)
    op.create_index(op.f('ix_document_index_specs_index_type'), 'document_index_specs', ['index_type'], unique=False)
    op.create_table('document_index_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=24), nullable=False),
    sa.Column('index_type', sa.Enum('vector', 'fulltext', 'graph', name='documentindextype'), nullable=False),
    sa.Column('actual_state', sa.Enum('absent', 'creating', 'present', 'deleting', 'failed', name='indexactualstate'), nullable=False),
    sa.Column('observed_version', sa.Integer(), nullable=False),
    sa.Column('index_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_last_reconciled', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'index_type', name='uq_document_index_status')
    )
    op.create_index(op.f('ix_document_index_statuses_actual_state'), 'document_index_statuses', ['actual_state'], unique=False)
    op.create_index(op.f('ix_document_index_statuses_document_id'), 'document_index_statuses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_index_statuses_id'), 'document_index_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_document_index_statuses_index_type'), 'document_index_statuses', ['index_type'], unique=False)
    op.drop_column('document', 'vector_index_status')
    op.drop_column('document', 'fulltext_index_status')
    op.drop_column('document', 'graph_index_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('graph_index_status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', 'SKIPPED', name='documentindexstatus'), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('fulltext_index_status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', 'SKIPPED', name='documentindexstatus'), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('vector_index_status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', 'SKIPPED', name='documentindexstatus'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_document_index_statuses_index_type'), table_name='document_index_statuses')
    op.drop_index(op.f('ix_document_index_statuses_id'), table_name='document_index_statuses')
    op.drop_index(op.f('ix_document_index_statuses_document_id'), table_name='document_index_statuses')
    op.drop_index(op.f('ix_document_index_statuses_actual_state'), table_name='document_index_statuses')
    op.drop_table('document_index_statuses')
    op.drop_index(op.f('ix_document_index_specs_index_type'), table_name='document_index_specs')
    op.drop_index(op.f('ix_document_index_specs_id'), table_name='document_index_specs')
    op.drop_index(op.f('ix_document_index_specs_document_id'), table_name='document_index_specs')
    op.drop_index(op.f('ix_document_index_specs_desired_state'), table_name='document_index_specs')
    op.drop_table('document_index_specs')
    # ### end Alembic commands ###
