"""empty message

Revision ID: eaec1fff0ffe
Revises: 4873db3367ce
Create Date: 2025-07-25 11:54:41.695017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaec1fff0ffe'
down_revision: Union[str, None] = '4873db3367ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.alter_column('api_key', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_api_key_is_system'), 'api_key', ['is_system'], unique=False)
    op.alter_column('audit_log', 'resource_type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_comment='Resource type',
               existing_nullable=True)
    op.alter_column('bot', 'type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('bot', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('chat', 'peer_type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('chat', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('collection', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('collection', 'type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('collection_summary', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document_index', 'index_type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('document_index', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('graph_index_merge_suggestions', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('invitation', 'role',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('llm_provider_models', 'api',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('message_feedback', 'type',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('message_feedback', 'tag',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('message_feedback', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('model_service_provider', 'status',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('model_service_provider', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('message_feedback', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('message_feedback', 'tag',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('message_feedback', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('llm_provider_models', 'api',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('invitation', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('graph_index_merge_suggestions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('document_index', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('document_index', 'index_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('document', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('collection_summary', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('collection', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('collection', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('chat', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('chat', 'peer_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('bot', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('bot', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('audit_log', 'resource_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_comment='Resource type',
               existing_nullable=True)
    op.drop_index(op.f('ix_api_key_is_system'), table_name='api_key')
    op.alter_column('api_key', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.drop_column('api_key', 'is_system')
    # ### end Alembic commands ###
