"""Add merge_suggestions table

Revision ID: c09204152091
Revises: add_index_audit_resource
Create Date: 2025-07-11 11:08:00.343928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09204152091'
down_revision: Union[str, None] = 'add_index_audit_resource'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_suggestions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('suggestion_batch_id', sa.String(length=24), nullable=False),
    sa.Column('entity_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('entity_ids_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('merge_reason', sa.Text(), nullable=False),
    sa.Column('suggested_target_entity', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='mergesuggestionstatus'), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'entity_ids_hash', 'gmt_deleted', name='uq_merge_suggestion')
    )
    op.create_index('idx_merge_suggestion_batch', 'merge_suggestions', ['collection_id', 'suggestion_batch_id'], unique=False)
    op.create_index('idx_merge_suggestion_collection_status', 'merge_suggestions', ['collection_id', 'status'], unique=False)
    op.create_index('idx_merge_suggestion_created', 'merge_suggestions', ['gmt_created'], unique=False)
    op.create_index('idx_merge_suggestion_expires', 'merge_suggestions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_merge_suggestions_collection_id'), 'merge_suggestions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_merge_suggestions_gmt_deleted'), 'merge_suggestions', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_merge_suggestions_status'), 'merge_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_merge_suggestions_suggestion_batch_id'), 'merge_suggestions', ['suggestion_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merge_suggestions_suggestion_batch_id'), table_name='merge_suggestions')
    op.drop_index(op.f('ix_merge_suggestions_status'), table_name='merge_suggestions')
    op.drop_index(op.f('ix_merge_suggestions_gmt_deleted'), table_name='merge_suggestions')
    op.drop_index(op.f('ix_merge_suggestions_collection_id'), table_name='merge_suggestions')
    op.drop_index('idx_merge_suggestion_expires', table_name='merge_suggestions')
    op.drop_index('idx_merge_suggestion_created', table_name='merge_suggestions')
    op.drop_index('idx_merge_suggestion_collection_status', table_name='merge_suggestions')
    op.drop_index('idx_merge_suggestion_batch', table_name='merge_suggestions')
    op.drop_table('merge_suggestions')
    # ### end Alembic commands ###
