"""empty message

Revision ID: bc0b9b1518d8
Revises: add_collection_summary
Create Date: 2025-07-14 11:35:10.725208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0b9b1518d8'
down_revision: Union[str, None] = 'add_collection_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER TYPE documentindextype ADD VALUE 'SUMMARY'"))
    op.alter_column('collection', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='LLM-generated summary',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'summary',
               existing_type=sa.TEXT(),
               comment='LLM-generated summary',
               existing_nullable=True)
    # ### end Alembic commands ###
