"""post-reset initial

Revision ID: 930bdb402fc1
Revises:
Create Date: 2026-04-29 08:55:30.795768

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "930bdb402fc1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_message",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("turn_id", sa.String(length=24), nullable=False),
        sa.Column("chat_id", sa.String(length=24), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("runtime_kind", sa.String(length=24), server_default="agent_runtime", nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("parts", sa.JSON(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id", name="uq_agent_message_turn"),
    )
    op.create_index("idx_agent_message_chat_created", "agent_message", ["chat_id", "gmt_created"], unique=False)
    op.create_index(op.f("ix_agent_message_chat_id"), "agent_message", ["chat_id"], unique=False)
    op.create_index(op.f("ix_agent_message_turn_id"), "agent_message", ["turn_id"], unique=False)
    op.create_table(
        "agent_turn",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("chat_id", sa.String(length=24), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("bot_id", sa.String(length=24), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("client_idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("model_profile", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("timeline_cursor", sa.Integer(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_finished", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "client_idempotency_key", name="uq_agent_turn_chat_idempotency"),
    )
    op.create_index("idx_agent_turn_chat_created", "agent_turn", ["chat_id", "gmt_created"], unique=False)
    op.create_index("idx_agent_turn_user_status", "agent_turn", ["user", "status"], unique=False)
    op.create_index(op.f("ix_agent_turn_bot_id"), "agent_turn", ["bot_id"], unique=False)
    op.create_index(op.f("ix_agent_turn_chat_id"), "agent_turn", ["chat_id"], unique=False)
    op.create_index(op.f("ix_agent_turn_request_id"), "agent_turn", ["request_id"], unique=True)
    op.create_index(op.f("ix_agent_turn_status"), "agent_turn", ["status"], unique=False)
    op.create_index(op.f("ix_agent_turn_user"), "agent_turn", ["user"], unique=False)
    op.create_table(
        "aperag_lineage_entity_alias",
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("alias_name", sa.String(length=512), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("merged_by", sa.String(length=256), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("collection_id", "alias_name"),
    )
    op.create_index(
        "ix_aperag_lineage_entity_alias_canonical",
        "aperag_lineage_entity_alias",
        ["collection_id", "canonical_name"],
        unique=False,
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_key_gmt_deleted"), "api_key", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_api_key_is_system"), "api_key", ["is_system"], unique=False)
    op.create_index(op.f("ix_api_key_status"), "api_key", ["status"], unique=False)
    op.create_index(op.f("ix_api_key_user"), "api_key", ["user"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True, comment="User ID"),
        sa.Column("username", sa.String(length=255), nullable=True, comment="Username"),
        sa.Column("resource_type", sa.String(length=50), nullable=True, comment="Resource type"),
        sa.Column("resource_id", sa.String(length=255), nullable=True, comment="Resource ID (extracted at query time)"),
        sa.Column("api_name", sa.String(length=255), nullable=False, comment="API operation name"),
        sa.Column("http_method", sa.String(length=10), nullable=False, comment="HTTP method (POST, PUT, DELETE)"),
        sa.Column("path", sa.String(length=512), nullable=False, comment="API path"),
        sa.Column("status_code", sa.Integer(), nullable=True, comment="HTTP status code"),
        sa.Column("request_data", sa.Text(), nullable=True, comment="Request data (JSON)"),
        sa.Column("response_data", sa.Text(), nullable=True, comment="Response data (JSON)"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error message if failed"),
        sa.Column("ip_address", sa.String(length=45), nullable=True, comment="Client IP address"),
        sa.Column("user_agent", sa.String(length=500), nullable=True, comment="User agent string"),
        sa.Column("request_id", sa.String(length=255), nullable=False, comment="Request ID for tracking"),
        sa.Column(
            "start_time", sa.BigInteger(), nullable=False, comment="Request start time (milliseconds since epoch)"
        ),
        sa.Column("end_time", sa.BigInteger(), nullable=True, comment="Request end time (milliseconds since epoch)"),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False, comment="Created time"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_api_name", "audit_log", ["api_name"], unique=False)
    op.create_index("idx_audit_gmt_created", "audit_log", ["gmt_created"], unique=False)
    op.create_index("idx_audit_http_method", "audit_log", ["http_method"], unique=False)
    op.create_index("idx_audit_request_id", "audit_log", ["request_id"], unique=False)
    op.create_index("idx_audit_resource_id", "audit_log", ["resource_id"], unique=False)
    op.create_index("idx_audit_resource_type", "audit_log", ["resource_type"], unique=False)
    op.create_index("idx_audit_start_time", "audit_log", ["start_time"], unique=False)
    op.create_index("idx_audit_status_code", "audit_log", ["status_code"], unique=False)
    op.create_index("idx_audit_user_id", "audit_log", ["user_id"], unique=False)
    op.create_table(
        "bot",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bot_gmt_deleted"), "bot", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_bot_is_system"), "bot", ["is_system"], unique=False)
    op.create_index(op.f("ix_bot_status"), "bot", ["status"], unique=False)
    op.create_index(op.f("ix_bot_user"), "bot", ["user"], unique=False)
    op.create_index(
        "uq_bot_user_type_system_active",
        "bot",
        ["user", "type", "is_system"],
        unique=True,
        postgresql_where=sa.text("gmt_deleted IS NULL AND is_system = TRUE"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("peer_type", sa.String(length=50), nullable=False),
        sa.Column("peer_id", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("bot_id", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_bot_id"), "chat", ["bot_id"], unique=False)
    op.create_index(op.f("ix_chat_gmt_deleted"), "chat", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_chat_status"), "chat", ["status"], unique=False)
    op.create_index(op.f("ix_chat_user"), "chat", ["user"], unique=False)
    op.create_index(
        "uq_chat_bot_peer_active",
        "chat",
        ["bot_id", "peer_type", "peer_id"],
        unique=True,
        postgresql_where=sa.text("gmt_deleted IS NULL"),
    )
    op.create_table(
        "collection",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("regen_lease_owner", sa.String(length=64), nullable=True),
        sa.Column("regen_lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collection_gmt_deleted"), "collection", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_collection_status"), "collection", ["status"], unique=False)
    op.create_index(op.f("ix_collection_user"), "collection", ["user"], unique=False)
    op.create_table(
        "collection_marketplace",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", name="uq_collection_marketplace_collection"),
    )
    op.create_index(
        "idx_collection_marketplace_collection_id", "collection_marketplace", ["collection_id"], unique=False
    )
    op.create_index("idx_collection_marketplace_gmt_deleted", "collection_marketplace", ["gmt_deleted"], unique=False)
    op.create_index(
        "idx_collection_marketplace_list", "collection_marketplace", ["status", "gmt_created"], unique=False
    )
    op.create_index("idx_collection_marketplace_status", "collection_marketplace", ["status"], unique=False)
    op.create_table(
        "config",
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("object_path", sa.Text(), nullable=True),
        sa.Column("doc_metadata", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_collection_id"), "document", ["collection_id"], unique=False)
    op.create_index(op.f("ix_document_content_hash"), "document", ["content_hash"], unique=False)
    op.create_index(op.f("ix_document_gmt_deleted"), "document", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_document_status"), "document", ["status"], unique=False)
    op.create_index(op.f("ix_document_user"), "document", ["user"], unique=False)
    op.create_index(
        "uq_document_collection_name_active",
        "document",
        ["collection_id", "name"],
        unique=True,
        postgresql_where=sa.text("gmt_deleted IS NULL"),
    )
    op.create_table(
        "document_index",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("parse_version", sa.String(length=16), nullable=False),
        sa.Column("modality", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("derived_artifact_path", sa.Text(), nullable=True),
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("tenant_scope_key", sa.String(length=64), nullable=False),
        sa.Column("is_serving", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "parse_version", "modality", name="uq_document_index_triple"),
    )
    op.create_index("idx_document_index_collection", "document_index", ["collection_id"], unique=False)
    op.create_index("idx_document_index_document_modality", "document_index", ["document_id", "modality"], unique=False)
    op.create_index("idx_document_index_status_modality", "document_index", ["status", "modality"], unique=False)
    op.create_index("idx_document_index_tenant_scope", "document_index", ["tenant_scope_key"], unique=False)
    op.create_index(
        "uniq_document_index_serving",
        "document_index",
        ["document_id", "modality"],
        unique=True,
        postgresql_where=sa.text("is_serving = TRUE"),
        sqlite_where=sa.text("is_serving = TRUE"),
    )
    op.create_table(
        "evaluation_dataset_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.String(length=32), nullable=False),
        sa.Column("case_key", sa.String(length=128), nullable=False),
        sa.Column("input_message", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=True),
        sa.Column("reference_context", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("case_metadata", sa.JSON(), nullable=True),
        sa.Column("sort_key", sa.Integer(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "case_key", name="uq_evaluation_dataset_item_case_key"),
    )
    op.create_index("idx_evaluation_dataset_items_dataset", "evaluation_dataset_items", ["dataset_id"], unique=False)
    op.create_index(
        op.f("ix_evaluation_dataset_items_gmt_deleted"), "evaluation_dataset_items", ["gmt_deleted"], unique=False
    )
    op.create_table(
        "evaluation_datasets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("schema_hint", sa.JSON(), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_datasets_collection", "evaluation_datasets", ["collection_id"], unique=False)
    op.create_index("idx_evaluation_datasets_user", "evaluation_datasets", ["user_id"], unique=False)
    op.create_index(op.f("ix_evaluation_datasets_gmt_deleted"), "evaluation_datasets", ["gmt_deleted"], unique=False)
    op.create_table(
        "evaluation_run_item_attempts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_item_id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("agent_chat_id", sa.String(length=24), nullable=True),
        sa.Column("agent_turn_id", sa.String(length=24), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("judge_result", sa.JSON(), nullable=True),
        sa.Column("score", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_reason", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_finished", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_item_id", "attempt_no", name="uq_evaluation_run_item_attempt_no"),
    )
    op.create_index(
        "idx_evaluation_run_item_attempts_item", "evaluation_run_item_attempts", ["run_item_id"], unique=False
    )
    op.create_index("idx_evaluation_run_item_attempts_run", "evaluation_run_item_attempts", ["run_id"], unique=False)
    op.create_table(
        "evaluation_run_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_dataset_item_id", sa.String(length=32), nullable=True),
        sa.Column("case_key", sa.String(length=128), nullable=False),
        sa.Column("sort_key", sa.Integer(), nullable=False),
        sa.Column("input_message", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=True),
        sa.Column("reference_context", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("case_metadata", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("best_score", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("latest_attempt_id", sa.String(length=32), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("judge_breakdown", sa.JSON(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_run_items_run", "evaluation_run_items", ["run_id"], unique=False)
    op.create_index("idx_evaluation_run_items_status", "evaluation_run_items", ["status"], unique=False)
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("bot_id", sa.String(length=24), nullable=False),
        sa.Column("dataset_id", sa.String(length=32), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=True),
        sa.Column("dataset_name", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("bot_config_snapshot", sa.JSON(), nullable=True),
        sa.Column("model_config_snapshot", sa.JSON(), nullable=True),
        sa.Column("answer_model", sa.String(length=64), nullable=True),
        sa.Column("judge_model", sa.String(length=64), nullable=True),
        sa.Column("judge_config", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_finished", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_evaluation_runs_bot", "evaluation_runs", ["bot_id"], unique=False)
    op.create_index("idx_evaluation_runs_collection", "evaluation_runs", ["collection_id"], unique=False)
    op.create_index("idx_evaluation_runs_dataset", "evaluation_runs", ["dataset_id"], unique=False)
    op.create_index("idx_evaluation_runs_status", "evaluation_runs", ["status"], unique=False)
    op.create_index("idx_evaluation_runs_user", "evaluation_runs", ["user_id"], unique=False)
    op.create_table(
        "export_task",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("object_store_path", sa.Text(), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_expires", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_export_task_expires", "export_task", ["status", "gmt_expires"], unique=False)
    op.create_index("idx_export_task_user_status", "export_task", ["user", "status"], unique=False)
    op.create_index(op.f("ix_export_task_collection_id"), "export_task", ["collection_id"], unique=False)
    op.create_index(op.f("ix_export_task_user"), "export_task", ["user"], unique=False)
    op.create_table(
        "graph_curation_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_finished", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_graph_curation_runs_collection_status", "graph_curation_runs", ["collection_id", "status"], unique=False
    )
    op.create_index(
        "idx_graph_curation_runs_user_created", "graph_curation_runs", ["user_id", "gmt_created"], unique=False
    )
    op.create_table(
        "graph_curation_suggestions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("entity_ids", sa.JSON(), nullable=False),
        sa.Column("entity_snapshots", sa.JSON(), nullable=False),
        sa.Column("target_entity_id", sa.String(length=255), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("operated_by", sa.String(length=256), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_operated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_graph_curation_suggestions_collection_created",
        "graph_curation_suggestions",
        ["collection_id", "gmt_created"],
        unique=False,
    )
    op.create_index(
        "idx_graph_curation_suggestions_collection_status",
        "graph_curation_suggestions",
        ["collection_id", "status"],
        unique=False,
    )
    op.create_index("idx_graph_curation_suggestions_run", "graph_curation_suggestions", ["run_id"], unique=False)
    op.create_table(
        "graph_hybrid_layout_cache",
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("backend_type", sa.String(length=32), nullable=False),
        sa.Column("max_entities", sa.Integer(), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column("points_json", sa.JSON(), nullable=False),
        sa.Column("cluster_labels", sa.JSON(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("collection_id", "cache_key"),
    )
    op.create_index(
        "idx_graph_hybrid_layout_cache_collection_updated",
        "graph_hybrid_layout_cache",
        ["collection_id", "gmt_updated"],
        unique=False,
    )
    op.create_table(
        "invitation",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("account_id", sa.String(length=24), nullable=False),
        sa.Column("provider_model_id", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("capability", sa.String(length=50), nullable=False),
        sa.Column("runner_type", sa.String(length=128), nullable=False),
        sa.Column("runner_config", sa.JSON(), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("max_input_tokens", sa.Integer(), nullable=True),
        sa.Column("max_output_tokens", sa.Integer(), nullable=True),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=True),
        sa.Column("supports_vision", sa.Boolean(), nullable=False),
        sa.Column("supports_tool_calling", sa.Boolean(), nullable=False),
        sa.Column("supports_multimodal_embedding", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_account_id"), "model", ["account_id"], unique=False)
    op.create_index(op.f("ix_model_capability"), "model", ["capability"], unique=False)
    op.create_index(op.f("ix_model_provider_model_id"), "model", ["provider_model_id"], unique=False)
    op.create_index(op.f("ix_model_status"), "model", ["status"], unique=False)
    op.create_table(
        "model_account",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("provider_type", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("encrypted_api_key", sa.Text(), nullable=False),
        sa.Column("auth_config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validation_error", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_account_name"), "model_account", ["name"], unique=False)
    op.create_index(op.f("ix_model_account_provider_type"), "model_account", ["provider_type"], unique=False)
    op.create_index(op.f("ix_model_account_user_id"), "model_account", ["user_id"], unique=False)
    op.create_table(
        "model_provider",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("provider_type", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("supported_capabilities", sa.JSON(), nullable=False),
        sa.Column("account_schema", sa.JSON(), nullable=False),
        sa.Column("default_base_url", sa.String(length=512), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_provider_provider_type"), "model_provider", ["provider_type"], unique=True)
    op.create_table(
        "model_use",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=False),
        sa.Column("scenario", sa.String(length=50), nullable=False),
        sa.Column("capability", sa.String(length=50), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("primary_model_id", sa.String(length=24), nullable=True),
        sa.Column("fallback_model_ids", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_use_primary_model_id"), "model_use", ["primary_model_id"], unique=False)
    op.create_index(op.f("ix_model_use_scenario"), "model_use", ["scenario"], unique=False)
    op.create_index(op.f("ix_model_use_user_id"), "model_use", ["user_id"], unique=False)
    op.create_table(
        "prompt_template",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("prompt_type", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=256), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_template_gmt_deleted"), "prompt_template", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_prompt_template_prompt_type"), "prompt_template", ["prompt_type"], unique=False)
    op.create_index(op.f("ix_prompt_template_scope"), "prompt_template", ["scope"], unique=False)
    op.create_index(op.f("ix_prompt_template_user_id"), "prompt_template", ["user_id"], unique=False)
    op.create_table(
        "searchhistory",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("collection_id", sa.String(length=24), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("vector_search", sa.JSON(), nullable=True),
        sa.Column("fulltext_search", sa.JSON(), nullable=True),
        sa.Column("graph_search", sa.JSON(), nullable=True),
        sa.Column("summary_search", sa.JSON(), nullable=True),
        sa.Column("vision_search", sa.JSON(), nullable=True),
        sa.Column("items", sa.JSON(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_searchhistory_collection_id"), "searchhistory", ["collection_id"], unique=False)
    op.create_index(op.f("ix_searchhistory_gmt_deleted"), "searchhistory", ["gmt_deleted"], unique=False)
    op.create_index(op.f("ix_searchhistory_user"), "searchhistory", ["user"], unique=False)
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "turn_feedback",
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.String(length=24), nullable=False),
        sa.Column("turn_id", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "turn_id"),
    )
    op.create_index(op.f("ix_turn_feedback_user"), "turn_feedback", ["user"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("chat_collection_id", sa.String(length=24), nullable=True),
        sa.Column("date_joined", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_chat_collection_id"), "user", ["chat_collection_id"], unique=False)
    op.create_table(
        "user_collection_subscription",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=24), nullable=False),
        sa.Column("collection_marketplace_id", sa.String(length=24), nullable=False),
        sa.Column("gmt_subscribed", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_subscription_gmt_deleted", "user_collection_subscription", ["gmt_deleted"], unique=False)
    op.create_index(
        "idx_user_subscription_marketplace", "user_collection_subscription", ["collection_marketplace_id"], unique=False
    )
    op.create_index("idx_user_subscription_user", "user_collection_subscription", ["user_id"], unique=False)
    op.create_index(
        "uq_user_subscription_marketplace_active",
        "user_collection_subscription",
        ["user_id", "collection_marketplace_id"],
        unique=True,
        postgresql_where=sa.text("gmt_deleted IS NULL"),
    )
    op.create_table(
        "user_quota",
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("quota_limit", sa.Integer(), nullable=False),
        sa.Column("current_usage", sa.Integer(), nullable=False),
        sa.Column("gmt_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gmt_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user", "key"),
    )
    op.create_table(
        "oauth_account",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("oauth_name", sa.String(length=100), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("account_id", sa.String(length=320), nullable=False),
        sa.Column("account_email", sa.String(length=320), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_account_account_id"), "oauth_account", ["account_id"], unique=False)
    op.create_index(op.f("ix_oauth_account_oauth_name"), "oauth_account", ["oauth_name"], unique=False)
    op.create_table(
        "aperag_lineage_entity",
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column(
            "source_lineage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_parts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("compacted_description", sa.Text(), nullable=True),
        sa.Column(
            "gmt_created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "gmt_updated", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("collection_id", "name"),
    )
    op.create_index(
        "idx_lineage_entity_collection_type_name",
        "aperag_lineage_entity",
        ["collection_id", "entity_type", "name"],
        unique=False,
    )
    op.create_index(
        "idx_lineage_entity_source_lineage_gin",
        "aperag_lineage_entity",
        ["source_lineage"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "aperag_lineage_relation",
        sa.Column("collection_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("target", sa.String(length=512), nullable=False),
        sa.Column("relation_type", sa.String(length=64), nullable=False),
        sa.Column(
            "evidence_lineage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "description_parts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("compacted_description", sa.Text(), nullable=True),
        sa.Column(
            "gmt_created", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "gmt_updated", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("collection_id", "source", "target", "relation_type"),
    )
    op.create_index(
        "idx_lineage_relation_collection_target_source_type",
        "aperag_lineage_relation",
        ["collection_id", "target", "source", "relation_type"],
        unique=False,
    )
    op.create_index(
        "idx_lineage_relation_evidence_lineage_gin",
        "aperag_lineage_relation",
        ["evidence_lineage"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_lineage_relation_evidence_lineage_gin", table_name="aperag_lineage_relation", postgresql_using="gin"
    )
    op.drop_index("idx_lineage_relation_collection_target_source_type", table_name="aperag_lineage_relation")
    op.drop_table("aperag_lineage_relation")
    op.drop_index("idx_lineage_entity_source_lineage_gin", table_name="aperag_lineage_entity", postgresql_using="gin")
    op.drop_index("idx_lineage_entity_collection_type_name", table_name="aperag_lineage_entity")
    op.drop_table("aperag_lineage_entity")
    op.drop_index(op.f("ix_oauth_account_oauth_name"), table_name="oauth_account")
    op.drop_index(op.f("ix_oauth_account_account_id"), table_name="oauth_account")
    op.drop_table("oauth_account")
    op.drop_table("user_quota")
    op.drop_index(
        "uq_user_subscription_marketplace_active",
        table_name="user_collection_subscription",
        postgresql_where=sa.text("gmt_deleted IS NULL"),
    )
    op.drop_index("idx_user_subscription_user", table_name="user_collection_subscription")
    op.drop_index("idx_user_subscription_marketplace", table_name="user_collection_subscription")
    op.drop_index("idx_user_subscription_gmt_deleted", table_name="user_collection_subscription")
    op.drop_table("user_collection_subscription")
    op.drop_index(op.f("ix_user_chat_collection_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_turn_feedback_user"), table_name="turn_feedback")
    op.drop_table("turn_feedback")
    op.drop_table("setting")
    op.drop_index(op.f("ix_searchhistory_user"), table_name="searchhistory")
    op.drop_index(op.f("ix_searchhistory_gmt_deleted"), table_name="searchhistory")
    op.drop_index(op.f("ix_searchhistory_collection_id"), table_name="searchhistory")
    op.drop_table("searchhistory")
    op.drop_index(op.f("ix_prompt_template_user_id"), table_name="prompt_template")
    op.drop_index(op.f("ix_prompt_template_scope"), table_name="prompt_template")
    op.drop_index(op.f("ix_prompt_template_prompt_type"), table_name="prompt_template")
    op.drop_index(op.f("ix_prompt_template_gmt_deleted"), table_name="prompt_template")
    op.drop_table("prompt_template")
    op.drop_index(op.f("ix_model_use_user_id"), table_name="model_use")
    op.drop_index(op.f("ix_model_use_scenario"), table_name="model_use")
    op.drop_index(op.f("ix_model_use_primary_model_id"), table_name="model_use")
    op.drop_table("model_use")
    op.drop_index(op.f("ix_model_provider_provider_type"), table_name="model_provider")
    op.drop_table("model_provider")
    op.drop_index(op.f("ix_model_account_user_id"), table_name="model_account")
    op.drop_index(op.f("ix_model_account_provider_type"), table_name="model_account")
    op.drop_index(op.f("ix_model_account_name"), table_name="model_account")
    op.drop_table("model_account")
    op.drop_index(op.f("ix_model_status"), table_name="model")
    op.drop_index(op.f("ix_model_provider_model_id"), table_name="model")
    op.drop_index(op.f("ix_model_capability"), table_name="model")
    op.drop_index(op.f("ix_model_account_id"), table_name="model")
    op.drop_table("model")
    op.drop_table("invitation")
    op.drop_index("idx_graph_hybrid_layout_cache_collection_updated", table_name="graph_hybrid_layout_cache")
    op.drop_table("graph_hybrid_layout_cache")
    op.drop_index("idx_graph_curation_suggestions_run", table_name="graph_curation_suggestions")
    op.drop_index("idx_graph_curation_suggestions_collection_status", table_name="graph_curation_suggestions")
    op.drop_index("idx_graph_curation_suggestions_collection_created", table_name="graph_curation_suggestions")
    op.drop_table("graph_curation_suggestions")
    op.drop_index("idx_graph_curation_runs_user_created", table_name="graph_curation_runs")
    op.drop_index("idx_graph_curation_runs_collection_status", table_name="graph_curation_runs")
    op.drop_table("graph_curation_runs")
    op.drop_index(op.f("ix_export_task_user"), table_name="export_task")
    op.drop_index(op.f("ix_export_task_collection_id"), table_name="export_task")
    op.drop_index("idx_export_task_user_status", table_name="export_task")
    op.drop_index("idx_export_task_expires", table_name="export_task")
    op.drop_table("export_task")
    op.drop_index("idx_evaluation_runs_user", table_name="evaluation_runs")
    op.drop_index("idx_evaluation_runs_status", table_name="evaluation_runs")
    op.drop_index("idx_evaluation_runs_dataset", table_name="evaluation_runs")
    op.drop_index("idx_evaluation_runs_collection", table_name="evaluation_runs")
    op.drop_index("idx_evaluation_runs_bot", table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index("idx_evaluation_run_items_status", table_name="evaluation_run_items")
    op.drop_index("idx_evaluation_run_items_run", table_name="evaluation_run_items")
    op.drop_table("evaluation_run_items")
    op.drop_index("idx_evaluation_run_item_attempts_run", table_name="evaluation_run_item_attempts")
    op.drop_index("idx_evaluation_run_item_attempts_item", table_name="evaluation_run_item_attempts")
    op.drop_table("evaluation_run_item_attempts")
    op.drop_index(op.f("ix_evaluation_datasets_gmt_deleted"), table_name="evaluation_datasets")
    op.drop_index("idx_evaluation_datasets_user", table_name="evaluation_datasets")
    op.drop_index("idx_evaluation_datasets_collection", table_name="evaluation_datasets")
    op.drop_table("evaluation_datasets")
    op.drop_index(op.f("ix_evaluation_dataset_items_gmt_deleted"), table_name="evaluation_dataset_items")
    op.drop_index("idx_evaluation_dataset_items_dataset", table_name="evaluation_dataset_items")
    op.drop_table("evaluation_dataset_items")
    op.drop_index(
        "uniq_document_index_serving",
        table_name="document_index",
        postgresql_where=sa.text("is_serving = TRUE"),
        sqlite_where=sa.text("is_serving = TRUE"),
    )
    op.drop_index("idx_document_index_tenant_scope", table_name="document_index")
    op.drop_index("idx_document_index_status_modality", table_name="document_index")
    op.drop_index("idx_document_index_document_modality", table_name="document_index")
    op.drop_index("idx_document_index_collection", table_name="document_index")
    op.drop_table("document_index")
    op.drop_index(
        "uq_document_collection_name_active", table_name="document", postgresql_where=sa.text("gmt_deleted IS NULL")
    )
    op.drop_index(op.f("ix_document_user"), table_name="document")
    op.drop_index(op.f("ix_document_status"), table_name="document")
    op.drop_index(op.f("ix_document_gmt_deleted"), table_name="document")
    op.drop_index(op.f("ix_document_content_hash"), table_name="document")
    op.drop_index(op.f("ix_document_collection_id"), table_name="document")
    op.drop_table("document")
    op.drop_table("config")
    op.drop_index("idx_collection_marketplace_status", table_name="collection_marketplace")
    op.drop_index("idx_collection_marketplace_list", table_name="collection_marketplace")
    op.drop_index("idx_collection_marketplace_gmt_deleted", table_name="collection_marketplace")
    op.drop_index("idx_collection_marketplace_collection_id", table_name="collection_marketplace")
    op.drop_table("collection_marketplace")
    op.drop_index(op.f("ix_collection_user"), table_name="collection")
    op.drop_index(op.f("ix_collection_status"), table_name="collection")
    op.drop_index(op.f("ix_collection_gmt_deleted"), table_name="collection")
    op.drop_table("collection")
    op.drop_index("uq_chat_bot_peer_active", table_name="chat", postgresql_where=sa.text("gmt_deleted IS NULL"))
    op.drop_index(op.f("ix_chat_user"), table_name="chat")
    op.drop_index(op.f("ix_chat_status"), table_name="chat")
    op.drop_index(op.f("ix_chat_gmt_deleted"), table_name="chat")
    op.drop_index(op.f("ix_chat_bot_id"), table_name="chat")
    op.drop_table("chat")
    op.drop_index(
        "uq_bot_user_type_system_active",
        table_name="bot",
        postgresql_where=sa.text("gmt_deleted IS NULL AND is_system = TRUE"),
    )
    op.drop_index(op.f("ix_bot_user"), table_name="bot")
    op.drop_index(op.f("ix_bot_status"), table_name="bot")
    op.drop_index(op.f("ix_bot_is_system"), table_name="bot")
    op.drop_index(op.f("ix_bot_gmt_deleted"), table_name="bot")
    op.drop_table("bot")
    op.drop_index("idx_audit_user_id", table_name="audit_log")
    op.drop_index("idx_audit_status_code", table_name="audit_log")
    op.drop_index("idx_audit_start_time", table_name="audit_log")
    op.drop_index("idx_audit_resource_type", table_name="audit_log")
    op.drop_index("idx_audit_resource_id", table_name="audit_log")
    op.drop_index("idx_audit_request_id", table_name="audit_log")
    op.drop_index("idx_audit_http_method", table_name="audit_log")
    op.drop_index("idx_audit_gmt_created", table_name="audit_log")
    op.drop_index("idx_audit_api_name", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_api_key_user"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_status"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_is_system"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_gmt_deleted"), table_name="api_key")
    op.drop_table("api_key")
    op.drop_index("ix_aperag_lineage_entity_alias_canonical", table_name="aperag_lineage_entity_alias")
    op.drop_table("aperag_lineage_entity_alias")
    op.drop_index(op.f("ix_agent_turn_user"), table_name="agent_turn")
    op.drop_index(op.f("ix_agent_turn_status"), table_name="agent_turn")
    op.drop_index(op.f("ix_agent_turn_request_id"), table_name="agent_turn")
    op.drop_index(op.f("ix_agent_turn_chat_id"), table_name="agent_turn")
    op.drop_index(op.f("ix_agent_turn_bot_id"), table_name="agent_turn")
    op.drop_index("idx_agent_turn_user_status", table_name="agent_turn")
    op.drop_index("idx_agent_turn_chat_created", table_name="agent_turn")
    op.drop_table("agent_turn")
    op.drop_index(op.f("ix_agent_message_turn_id"), table_name="agent_message")
    op.drop_index(op.f("ix_agent_message_chat_id"), table_name="agent_message")
    op.drop_index("idx_agent_message_chat_created", table_name="agent_message")
    op.drop_table("agent_message")
    # ### end Alembic commands ###
