"""phase8_task39_legacy_orm_carve

Revision ID: a639b0e5515f
Revises: 6a8fc31427d9
Create Date: 2026-04-25 11:43:39.974509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a639b0e5515f'
down_revision: Union[str, None] = '6a8fc31427d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_questions_question_set_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('idx_question_sets_collection_id'), table_name='question_sets')
    op.drop_index(op.f('idx_question_sets_user_id'), table_name='question_sets')
    op.drop_table('question_sets')
    op.drop_index(op.f('idx_evaluation_items_evaluation_id'), table_name='evaluation_items')
    op.drop_index(op.f('ix_evaluation_items_status'), table_name='evaluation_items')
    op.drop_table('evaluation_items')
    op.drop_index(op.f('idx_evaluations_collection_id'), table_name='evaluations')
    op.drop_index(op.f('idx_evaluations_status'), table_name='evaluations')
    op.drop_index(op.f('idx_evaluations_user_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_constraint(op.f('uq_chat_bot_peer_deleted'), 'chat', type_='unique')
    op.create_index('uq_chat_bot_peer_active', 'chat', ['bot_id', 'peer_type', 'peer_id'], unique=True, postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.drop_constraint(op.f('uq_model_service_provider_name_deleted'), 'model_service_provider', type_='unique')
    op.create_index('uq_model_service_provider_name_active', 'model_service_provider', ['name'], unique=True, postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.drop_constraint(op.f('idx_user_marketplace_history_unique'), 'user_collection_subscription', type_='unique')
    op.create_index('uq_user_subscription_marketplace_active', 'user_collection_subscription', ['user_id', 'collection_marketplace_id'], unique=True, postgresql_where=sa.text('gmt_deleted IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_subscription_marketplace_active', table_name='user_collection_subscription', postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.create_unique_constraint(op.f('idx_user_marketplace_history_unique'), 'user_collection_subscription', ['user_id', 'collection_marketplace_id', 'gmt_deleted'])
    op.drop_index('uq_model_service_provider_name_active', table_name='model_service_provider', postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.create_unique_constraint(op.f('uq_model_service_provider_name_deleted'), 'model_service_provider', ['name', 'gmt_deleted'])
    op.drop_index('uq_chat_bot_peer_active', table_name='chat', postgresql_where=sa.text('gmt_deleted IS NULL'))
    op.create_unique_constraint(op.f('uq_chat_bot_peer_deleted'), 'chat', ['bot_id', 'peer_type', 'peer_id', 'gmt_deleted'])
    op.create_table('evaluations',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('question_set_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('agent_llm_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('judge_llm_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('gmt_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluations_pkey'))
    )
    op.create_index(op.f('idx_evaluations_user_id'), 'evaluations', ['user_id'], unique=False)
    op.create_index(op.f('idx_evaluations_status'), 'evaluations', ['status'], unique=False)
    op.create_index(op.f('idx_evaluations_collection_id'), 'evaluations', ['collection_id'], unique=False)
    op.create_table('evaluation_items',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('evaluation_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ground_truth', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rag_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rag_answer_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_judge_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llm_judge_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmt_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluation_items_pkey'))
    )
    op.create_index(op.f('ix_evaluation_items_status'), 'evaluation_items', ['status'], unique=False)
    op.create_index(op.f('idx_evaluation_items_evaluation_id'), 'evaluation_items', ['evaluation_id'], unique=False)
    op.create_table('question_sets',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gmt_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('question_sets_pkey'))
    )
    op.create_index(op.f('idx_question_sets_user_id'), 'question_sets', ['user_id'], unique=False)
    op.create_index(op.f('idx_question_sets_collection_id'), 'question_sets', ['collection_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('question_set_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ground_truth', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gmt_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('gmt_deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.create_index(op.f('idx_questions_question_set_id'), 'questions', ['question_set_id'], unique=False)
    # ### end Alembic commands ###
