config:
  get:
    summary: Get system configuration
    description: Get system configuration
    tags:
      - config
    security:
      - BearerAuth: []
    responses:
      '200':
        description: System configuration
        content:
          application/json:
            schema:
              $ref: '../components/schemas/config.yaml#/config'
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '../components/schemas/common.yaml#/failResponse'