name: PULL-REQUEST-LABEL-SIZE

on:
  pull_request_target:
    types: [ edited, opened, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set size label
        run: |
          bash .github/utils/utils.sh --type 15 \
              --github-token "${{ env.GITHUB_TOKEN }}" \
              --pr-number ${{ github.event.pull_request.number }}
